# Generated by Django 3.2.10 on 2023-11-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('u_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('pas', models.CharField(blank=True, max_length=50, null=True)),
                ('mob', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='adcontact',
        ),
    ]
