# Generated by Django 3.2.10 on 2023-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdb',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
