# Generated by Django 3.2.10 on 2023-11-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0002_regdb_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdb',
            name='loc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
