# Generated by Django 4.2.7 on 2023-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0003_regdb_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('b_name', models.CharField(blank=True, max_length=100, null=True)),
                ('b_mobile', models.IntegerField(blank=True, null=True)),
                ('b_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('loc', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
