# Generated by Django 4.2.7 on 2023-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0004_bookdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('u_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('pas', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
