# Generated by Django 4.2.7 on 2023-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0006_u_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
