# Generated by Django 4.2.7 on 2023-12-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0007_feedbackdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='u_contact',
            new_name='u_contactDB',
        ),
    ]
